(function(){
  "use strict";
  function getStore(){
    if(window.Combinvest&&window.Combinvest.store) return window.Combinvest.store;
    return {get:function(k){try{return localStorage.getItem(k);}catch(e){return null;}},
            set:function(k,v){try{localStorage.setItem(k,v);}catch(e){}}};
  }
  var chart=document.getElementById("chart"),form=document.getElementById("form");if(!chart||!form)return;
  var params=new URLSearchParams(location.search),mode=params.get("tool")||"sparen",customerId=(params.get("customerId")||"local-demo").replace(/[^a-zA-Z0-9_-]/g,"_"),analysisId=params.get("analysisId")||"",key="combinvest.crm.customer."+customerId+".wealth-"+mode+".v1";
  var style=document.createElement("style");style.textContent='.grid>.card:last-child{padding:22px 24px 20px}.metrics{gap:12px}.metric{border:1px solid #e2e9f3;background:#fff;padding:16px 17px;border-radius:14px}.metric:first-child{background:linear-gradient(135deg,#10234a,#3a57f5);border-color:transparent;color:#fff;box-shadow:0 12px 28px rgba(58,87,245,.18)}.metric:first-child small{color:#dfe7ff}.metric b{display:block;margin-top:5px;font-size:24px}.wealth-legend{display:flex;gap:9px;flex-wrap:wrap;margin:18px 0 10px}.wealth-legend span{display:flex;align-items:center;gap:7px;padding:7px 10px;border:1px solid #e4eaf4;border-radius:999px;background:#fff;color:#5e6d85;font-size:11px;font-weight:800}.wealth-legend i{width:18px;height:4px;border-radius:9px}.wealth-chart-wrap{position:relative;margin-top:2px;border-radius:17px;background:linear-gradient(180deg,#f5f8ff 0%,#fff 80%);border:1px solid #dfe7f3;overflow:hidden;box-shadow:inset 0 1px 0 #fff}.chart{height:350px;margin:0;display:block}.chart .gridline{stroke:#dfe7f2;stroke-width:1}.chart .axis-label{fill:#718096;font:10px Manrope,system-ui,sans-serif}.chart .area{fill:url(#wealthArea)}.chart .series{fill:none;stroke-linecap:round;stroke-linejoin:round;filter:drop-shadow(0 3px 3px rgba(58,87,245,.1))}.chart .line{stroke:#3a57f5;stroke-width:4}.chart .line2{stroke:#ef8b24;stroke-width:3}.chart .line3{stroke:#99a7bc;stroke-width:2.5;stroke-dasharray:7 7}.chart .cursor{stroke:#315fe7;stroke-width:1.2;stroke-dasharray:4 4}.chart .point{fill:#fff;stroke-width:4}.chart-tip{position:absolute;display:none;pointer-events:none;z-index:5;min-width:230px;padding:13px 15px;border-radius:13px;background:#0f1b36;color:#fff;box-shadow:0 16px 38px rgba(15,27,54,.28);font-size:12px}.chart-tip b{display:block;font-size:14px;margin-bottom:7px}.chart-tip span{display:flex;justify-content:space-between;gap:18px;margin-top:5px}.chart-tip i{font-style:normal;color:#cdd6eb}.note{margin:11px 2px 0!important;font-size:11.5px!important;color:#65738a!important}@media(max-width:700px){.chart{height:270px;min-width:680px}.wealth-chart-wrap{overflow-x:auto}.metrics{grid-template-columns:1fr!important}}';document.head.appendChild(style);
  document.querySelectorAll('a[href]').forEach(function(a){try{var u=new URL(a.getAttribute("href"),location.href);if(u.origin===location.origin){u.searchParams.set("customerId",customerId);if(analysisId)u.searchParams.set("analysisId",analysisId);a.href=u.pathname.split("/").pop()+u.search+u.hash;}}catch(e){}});
  var tabs=document.getElementById("tabs");if(tabs)tabs.addEventListener("click",function(e){var b=e.target.closest("button");if(!b)return;e.preventDefault();e.stopImmediatePropagation();var names=["sparen","zins","start","inflation","kosten","ziel","3a","steuer"],buttons=Array.from(tabs.querySelectorAll("button")),next=names[buttons.indexOf(b)]||"sparen",target="vermoegensrechner.html?tool="+encodeURIComponent(next)+"&customerId="+encodeURIComponent(customerId);if(analysisId)target+="&analysisId="+encodeURIComponent(analysisId);location.href=target;},true);
  function num(id,fallback){var e=document.getElementById(id);return e?+e.value:(fallback||0);}function money(n){return "CHF "+Math.round(n).toLocaleString("de-CH");}function compact(n){if(n>=1000000)return "CHF "+(n/1000000).toFixed(n>=10000000?0:1)+" Mio.";if(n>=1000)return "CHF "+Math.round(n/1000)+"k";return "CHF "+Math.round(n);}
  function fv(cap,monthly,years,rate){var m=rate/1200,n=years*12;return m?cap*Math.pow(1+m,n)+monthly*(Math.pow(1+m,n)-1)/m:cap+monthly*n;}
  function requiredMonthly(){var target=num("target"),cap=num("capital"),years=num("years",1),rate=num("rate"),m=rate/1200,n=years*12,grown=cap*Math.pow(1+m,n);return m?Math.max(0,(target-grown)*m/(Math.pow(1+m,n)-1)):Math.max(0,(target-cap)/n);}
  function series(){var years=Math.max(1,mode==="steuer"?1:num("years",25)),cap=num("capital"),monthly=num("monthly"),rate=num("rate"),rows=[];
    function add(label,color,dash,fn){var vals=[];for(var y=0;y<=years;y++)vals.push(Math.max(0,fn(y)));rows.push({label:label,color:color,dash:dash,values:vals});}
    if(mode==="inflation"){add("Heutiger Betrag","#10264b",true,function(){return cap;});add("Kaufkraft","#3a57f5",false,function(y){return cap/Math.pow(1+num("inflation")/100,y);});}
    else if(mode==="3a"){var annual=num("contribution");add("Entwicklung","#3a57f5",false,function(y){return fv(0,annual/12,y,4);});add("Einzahlungen","#10264b",true,function(y){return annual*y;});}
    else if(mode==="ziel"){var needed=requiredMonthly();add("Entwicklung","#3a57f5",false,function(y){return fv(cap,needed,y,rate);});add("Einzahlungen","#10264b",true,function(y){return cap+needed*12*y;});}
    else if(mode==="steuer"){var income=num("income"),tax=num("tax");rows=[{label:"Bruttoeinkommen",color:"#3a57f5",values:[income,income]},{label:"Nach Abzug",color:"#24b8a6",values:[income,income-income*tax/100]}];}
    else{add(mode==="zins"?"Entwicklung Rendite 1":"Entwicklung","#3a57f5",false,function(y){return fv(cap,monthly,y,rate);});if(mode==="zins")add("Entwicklung Rendite 2","#24b8a6",false,function(y){return fv(cap,monthly,y,num("rate2"));});if(mode==="start")add("Später starten","#24b8a6",false,function(y){return fv(cap,monthly,Math.max(0,y-num("delay")),rate);});if(mode==="kosten")add("Nach Kosten","#24b8a6",false,function(y){return fv(cap,monthly,y,Math.max(0,rate-num("ter")));});add("Einzahlungen","#10264b",true,function(y){return cap+monthly*12*y;});}
    return {years:years,rows:rows};
  }
  var current=null,tip=null,legend=null,wrap=null;
  var visualStyle=document.createElement("style");visualStyle.textContent='.wealth-legend span{font-size:12px}.chart{width:100%}.chart .axis-label{fill:#5f6f88;font:600 12px Manrope,system-ui,sans-serif}.chart-tip{background:#10264b}@media(max-width:700px){.grid>.card:last-child{padding:18px 12px}.chart{height:250px;min-width:0}.wealth-chart-wrap{overflow:hidden}.chart .axis-label{font-size:13px}.chart-tip{min-width:205px;max-width:calc(100% - 16px)}}';document.head.appendChild(visualStyle);
  function points(values,max){return values.map(function(v,i){return (58+i/(values.length-1||1)*672)+","+(282-v/max*226);}).join(" ");}
  function renderChart(){current=series();var max=1;current.rows.forEach(function(r){r.values.forEach(function(v){max=Math.max(max,v);});});var first=current.rows[0],firstPoints=points(first.values,max),area="58,282 "+firstPoints+" 730,282";var svg='<defs><linearGradient id="wealthArea" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#3a57f5" stop-opacity=".24"/><stop offset="1" stop-color="#3a57f5" stop-opacity=".02"/></linearGradient></defs>';
    for(var g=0;g<5;g++){var gy=56+g*56.5,gv=max*(1-g/4);svg+='<line class="gridline" x1="58" y1="'+gy+'" x2="730" y2="'+gy+'"/><text class="axis-label" x="8" y="'+(gy+4)+'">'+compact(gv)+'</text>';}
    svg+='<polygon class="area" points="'+area+'"/>';
    current.rows.forEach(function(r,i){svg+='<polyline class="series line'+(i+1)+'" style="stroke:'+r.color+(r.dash?';stroke-dasharray:7 7':'')+'" points="'+points(r.values,max)+'"/>';});
    svg+='<text class="axis-label" x="58" y="307">Heute</text><text class="axis-label" x="380" y="307" text-anchor="middle">Jahr '+Math.round(current.years/2)+'</text><text class="axis-label" x="730" y="307" text-anchor="end">Jahr '+current.years+'</text><line id="wealthCursor" class="cursor" x1="58" y1="52" x2="58" y2="282" visibility="hidden"/>';
    current.rows.forEach(function(r,i){svg+='<circle id="wealthPoint'+i+'" class="point" cx="58" cy="282" r="5" style="stroke:'+r.color+'" visibility="hidden"/>';});chart.setAttribute("viewBox","0 0 760 325");chart.setAttribute("aria-label","Vermögensentwicklung über "+current.years+" Jahre");chart.innerHTML=svg;legend.innerHTML=current.rows.map(function(r){return '<span><i style="background:'+r.color+'"></i>'+r.label+'</span>';}).join("");var note=document.getElementById("note");if(note)note.textContent="Fahren Sie über das Diagramm, um die Werte für jedes Jahr zu sehen.";chart.dataset.max=max;}
  function showTip(ev){if(!current)return;var box=chart.getBoundingClientRect(),ratio=Math.max(0,Math.min(1,(ev.clientX-box.left)/box.width)),year=Math.round(ratio*current.years),max=+chart.dataset.max||1,x=58+ratio*672;var cursor=document.getElementById("wealthCursor");cursor.setAttribute("x1",x);cursor.setAttribute("x2",x);cursor.setAttribute("visibility","visible");var rows=current.rows.map(function(r,i){var value=r.values[year]||0,y=282-value/max*226,p=document.getElementById("wealthPoint"+i);p.setAttribute("cx",x);p.setAttribute("cy",y);p.setAttribute("visibility","visible");return '<span><i>'+r.label+'</i><strong>'+money(value)+'</strong></span>';});tip.innerHTML='<b>'+(year===0?'Heute':'Jahr '+year)+'</b>'+rows.join("");tip.style.display="block";tip.style.left=Math.max(8,Math.min(wrap.clientWidth-tip.offsetWidth-8,ev.clientX-box.left+12))+"px";tip.style.top=Math.max(8,ev.clientY-box.top-18)+"px";}
  function hideTip(){tip.style.display="none";var cursor=document.getElementById("wealthCursor");if(cursor)cursor.setAttribute("visibility","hidden");current.rows.forEach(function(_,i){var p=document.getElementById("wealthPoint"+i);if(p)p.setAttribute("visibility","hidden");});}
  function save(){var inputs={};form.querySelectorAll("input").forEach(function(x){inputs[x.id]=+x.value;});try{getStore().set(key,JSON.stringify({customerId:customerId,module:"wealth-"+mode,updatedAt:new Date().toISOString(),data:{inputs:inputs}}));}catch(e){}}
  ((window.Combinvest&&window.Combinvest.ready)||Promise.resolve()).then(function(){try{var record=JSON.parse(getStore().get(key)||"null");if(record&&record.data&&record.data.inputs)Object.keys(record.data.inputs).forEach(function(id){var e=document.getElementById(id);if(e){e.value=record.data.inputs[id];e.dispatchEvent(new Event("input",{bubbles:true}));}});}catch(e){}});
  wrap=document.createElement("div");wrap.className="wealth-chart-wrap";chart.parentNode.insertBefore(wrap,chart);wrap.appendChild(chart);legend=document.createElement("div");legend.className="wealth-legend";wrap.parentNode.insertBefore(legend,wrap);tip=document.createElement("div");tip.className="chart-tip";tip.setAttribute("role","status");wrap.appendChild(tip);form.addEventListener("input",function(){save();renderChart();});chart.addEventListener("pointermove",showTip);chart.addEventListener("pointerleave",hideTip);renderChart();
})();
